<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Configurations>Debug;Release;Testing</Configurations>
		<Nullable>enable</Nullable>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Unit\Features\Shared\Components\ContentBlock\**" />
		<EmbeddedResource Remove="Unit\Features\Shared\Components\ContentBlock\**" />
		<None Remove="Unit\Features\Shared\Components\ContentBlock\**" />
	</ItemGroup>

	<ItemGroup>
		<Compile Remove="Extensions\StringExtensions.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="9.0.7" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="NUnit" Version="3.14.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
		<PackageReference Include="Umbraco.Cms.Tests.Integration" Version="16.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\UmbracoDemoSite.Web\UmbracoDemoSite.Web.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="..\UmbracoDemoSite.Web\bin\$(Configuration)\net9.0\UmbracoDemoSite.Web.deps.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>testhost.deps.json</Link>
		</None>
	</ItemGroup>
</Project>
